services:
  # Backend API Service
  - type: web
    name: jitsjournal-backend
    runtime: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        value: jitsjournal-videos
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_ENTHUSIAST_PRICE_ID
        sync: false
      - key: VITE_STRIPE_ENTHUSIAST_PRICE_ID
        sync: false
      - key: STRIPE_GYM_PRO_PRICE_ID
        sync: false
      - key: VITE_STRIPE_GYM_PRO_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: VITE_APP_URL
        value: https://jitsjournal.onrender.com
      - key: PORT
        value: 10000
